#!/bin/bash
#8Mi-ClashControl <Powered By Clash>

# export area
export http_proxy=
export https_proxy=
export ftp_proxy=

# custom command
bmi_clashHelp(){
    echo "当前运行状态"bmi_clashIsRunning
    echo '[8Mi-ClashController] 未知的指令 不过可以看看如下帮助
    用法: bmiclash [start|stop|reload]'
}

bmi_clashReloadHelp(){
    echo '[8Mi-ClashController] 重载指令帮助
    用法: bmiclash reload [config|ui]
    重载指令详细讲解:
        - 配置文件: bmiclash reload config
        - UI界面: bmiclash reload ui '
}

bmi_clashIsRunning(){
    tmux_result=`tmux ls`
    echo $tmux_result | grep "clash: " > /dev/null
        if [ $? == 0 ]
        then
            echo 1
        else
            echo 0
        fi
}

bmi_clash_getConfig(){
    bmi_clash_get_failed_count=0
    wget -O config.yaml "$(grep "sub_link=" clash_settings.config|sed 's/sub_link=//g')" > /dev/null
    if [ 0 -ne $? ]
    then
        if [ $bmi_clash_get_failed_count == 0 ]
        then
            echo "[8Mi-ClashController] 获取失败,正在重试(直到提示成功即可)"
        fi
            bmi_clash_get_failed_count=$(expr $bmi_clash_get_failed_count + 1)
            echo $bmi_clash_get_failed_count
            bmi_clash_getConfig
    else
        bmi_clash_get_failed_count=0
        echo "[8Mi-ClashController] 获取成功,正在检查配置文件"
    fi
}

bmi_clash_addConfig(){
    if  [ $(cat ./config.yaml | grep $1) -z "" ]
    then
        if  [ $blank == 0 ]
        then
            echo -e "\n"$1": "$2 >> ./config.yaml
            blank=1
        else
            echo $1": "$2 >> ./config.yaml
        fi
        echo "[8Mi-ClashController]  设置参数"\"$1\""为"\"$2\"
    fi
}

bmi_startClash(){
    if [ $(bmi_clashIsRunning) == 1 ]
        then
        echo "[8Mi-ClashController] Clash已加载,若需要重载配置,请输入 \" bmiclash reload config \""
        exit
    fi
    echo "[8Mi-ClashController] 正在加载Clash中,请稍等"
    tmux new-session -s clash -n core -d
    bmi_reloadClashConfig
    tmux new-window -t clash -n setting
    tmux send-keys -t clash:setting '#8Mi-ClashControl<Powered By Clash>' Enter
    bmi_reloadClashUI
    #echo '#!/bin/bash
    #export http_proxy="http://127.0.0.1:7890"
    #export https_proxy=$http_proxy
    #export ftp_proxy=$http_proxy
    #export SOCKS_SERVER="socks5://127.0.0.1:7890"
    #export no_proxy="localhost, 127.0.0.1, ::1"' > ./env_proxy.sh
    echo "[8Mi-ClashController] 正在调整系统设置里的系统代理参数"
    gsettings set org.gnome.system.proxy mode 'manual'
    gsettings set org.gnome.system.proxy.http port 7890
    gsettings set org.gnome.system.proxy.http host '127.0.0.1'
    gsettings set org.gnome.system.proxy.socks port 7891
    gsettings set org.gnome.system.proxy.socks host '127.0.0.1'
    gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '::1']"
    echo "[8Mi-ClashController] 系统代理参数设置成功"
}

bmi_reloadClashConfig(){
    if [ $(bmi_clashIsRunning) == 0 ]
        then
        echo "[8Mi-ClashController] Clash未加载,无效操作"
        exit
    fi
    echo "[8Mi-ClashController] 开始获取订阅配置文件中 ( 若显示进度条并且提示100%则提示获取成功 ) "
    bmi_clash_getConfig
    blank=0
    bmi_clash_addConfig "mixed-port" "7890"
    bmi_clash_addConfig "allow-lan" "false"
    bmi_clash_addConfig "mode" "Rule"
    bmi_clash_addConfig "log-level" "info"
    bmi_clash_addConfig "external-controller" "127.0.0.1:9090"
    echo "[8Mi-ClashController] 设置完毕,正在加载(或重载)Clash主程序"
    tmux send-keys -t clash:core C-c './clash -d ./' Enter
    echo "[8Mi-ClashController] Clash主程序以及界面程序加载完毕(也许是)"
}

bmi_reloadClashUI(){
    if [ $(bmi_clashIsRunning) == 0 ]
        then
        echo "[8Mi-ClashController] Clash未加载,无效操作"
        exit
    fi
    echo "[8Mi-ClashController] 正在加载(或重载)Clash界面程序"
    tmux send-keys -t clash:setting C-c 'browser -enable-gpu-rasterization --disable-pings --media-router=0 --enable-remote-extensions --load-extension= --window-size=1280,720 --app='$(grep "clash_dashboard=" clash_settings.config|sed 's/clash_dashboard=//g') Enter
    echo "[8Mi-ClashController] Clash界面程序加载完毕(或许是)"
}

bmi_stopClash(){
    if [ $(bmi_clashIsRunning) == 0 ]
        then
        echo "[8Mi-ClashController] Clash已停止"
        exit
    fi
    echo "[8Mi-ClashController] 正在停止Clash主程序以及界面程序"
    gsettings set org.gnome.system.proxy mode 'none'
    tmux kill-session -t clash
    echo "[8Mi-ClashController] 停止完毕"
}

# run area
case "$1" in
    "start")
        bmi_startClash
        ;;
    "stop")
        bmi_stopClash
        ;;
    "reload")
        case "$2" in
            "config")
                bmi_reloadClashConfig
                ;;
            "ui")
                bmi_reloadClashUI
                ;;
            *)
                bmi_clashReloadHelp
                ;;
        esac
        ;;
    *)
        bmi_clashHelp
        ;;
esac